version: '3.8'

services:
  mysql:
    image: mysql:8.0.33 
    container_name: gestao_vagas_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # Senha do usuário root do MySQL
      MYSQL_DATABASE: gestao_vagas       # Nome do banco de dados
      MYSQL_USER: root                 # Nome de usuário do banco de dados
      MYSQL_PASSWORD: root123         # Senha do usuário do banco de dados
    ports:
      - "3306:3306"  # Porta exposta para conectar ao banco
    networks:
      - mysql_network

networks:
  mysql_network:
    driver: bridge
